---
- name: Setup oVirt environment
  hosts: localhost
  connection: local
  vars_files:
    - "../group_vars/all/vars"
  tasks:
    - debug: var=manageiq
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=manageiq.event_target

    - block:
        - name: Include oVirt password
          no_log: true
          include_vars: ovirt_password.yml

        - name: Obtain SSO token
          no_log: false
          ovirt_auth:
            url: "{{ url }}"
            username: "{{ username }}"
            password: "{{ password }}"
            ca_file: "{{ ca_file }}"
         
        - name: set state of rhv host
          ovirt_hosts:
            auth: "{{ ovirt_auth }}"
            state: "{{ rhv_host_state }}"
            name: "{{ rhv_hostname }}"
            wait: true
        
        - name: update service
          command: curl -H "Authorization{{":"}} Basic {{ manageiq.api_token }}" -k -d '{"action"{{":"}} "edit","resource"{{":"}} {"description"{{":"}} "i just killed rhv"}}' Content-Type{{":"}} application/json -X POST https://cfmeldo1.rdu.salab.redhat.com/api/{{ manageiq.service }}
          register: curlreq

        - debug: var=curlreq



      always:
        - name: Revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
